// Code generated by MockGen. DO NOT EDIT.
// Source: books.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "bookshelf/internal/models"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBooksRepository is a mock of BooksRepository interface.
type MockBooksRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBooksRepositoryMockRecorder
}

// MockBooksRepositoryMockRecorder is the mock recorder for MockBooksRepository.
type MockBooksRepositoryMockRecorder struct {
	mock *MockBooksRepository
}

// NewMockBooksRepository creates a new mock instance.
func NewMockBooksRepository(ctrl *gomock.Controller) *MockBooksRepository {
	mock := &MockBooksRepository{ctrl: ctrl}
	mock.recorder = &MockBooksRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBooksRepository) EXPECT() *MockBooksRepositoryMockRecorder {
	return m.recorder
}

// CreateBook mocks base method.
func (m *MockBooksRepository) CreateBook(ctx context.Context, in models.BookRequest) (models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBook", ctx, in)
	ret0, _ := ret[0].(models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBook indicates an expected call of CreateBook.
func (mr *MockBooksRepositoryMockRecorder) CreateBook(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBook", reflect.TypeOf((*MockBooksRepository)(nil).CreateBook), ctx, in)
}

// DeleteBook mocks base method.
func (m *MockBooksRepository) DeleteBook(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBook", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBook indicates an expected call of DeleteBook.
func (mr *MockBooksRepositoryMockRecorder) DeleteBook(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBook", reflect.TypeOf((*MockBooksRepository)(nil).DeleteBook), ctx, id)
}

// GetBooks mocks base method.
func (m *MockBooksRepository) GetBooks(ctx context.Context, limit, offset int) ([]models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBooks", ctx, limit, offset)
	ret0, _ := ret[0].([]models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBooks indicates an expected call of GetBooks.
func (mr *MockBooksRepositoryMockRecorder) GetBooks(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBooks", reflect.TypeOf((*MockBooksRepository)(nil).GetBooks), ctx, limit, offset)
}

// GetDetails mocks base method.
func (m *MockBooksRepository) GetDetails(ctx context.Context, id uint64) (models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetails", ctx, id)
	ret0, _ := ret[0].(models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetails indicates an expected call of GetDetails.
func (mr *MockBooksRepositoryMockRecorder) GetDetails(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetails", reflect.TypeOf((*MockBooksRepository)(nil).GetDetails), ctx, id)
}

// MarkOutOfStock mocks base method.
func (m *MockBooksRepository) MarkOutOfStock(ctx context.Context, id uint64) (models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkOutOfStock", ctx, id)
	ret0, _ := ret[0].(models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkOutOfStock indicates an expected call of MarkOutOfStock.
func (mr *MockBooksRepositoryMockRecorder) MarkOutOfStock(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkOutOfStock", reflect.TypeOf((*MockBooksRepository)(nil).MarkOutOfStock), ctx, id)
}

// RecommendBooks mocks base method.
func (m *MockBooksRepository) RecommendBooks(ctx context.Context, limit int) ([]models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecommendBooks", ctx, limit)
	ret0, _ := ret[0].([]models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecommendBooks indicates an expected call of RecommendBooks.
func (mr *MockBooksRepositoryMockRecorder) RecommendBooks(ctx, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecommendBooks", reflect.TypeOf((*MockBooksRepository)(nil).RecommendBooks), ctx, limit)
}

// UpdateBook mocks base method.
func (m *MockBooksRepository) UpdateBook(ctx context.Context, id uint64, in models.BookRequest) (models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBook", ctx, id, in)
	ret0, _ := ret[0].(models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBook indicates an expected call of UpdateBook.
func (mr *MockBooksRepositoryMockRecorder) UpdateBook(ctx, id, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBook", reflect.TypeOf((*MockBooksRepository)(nil).UpdateBook), ctx, id, in)
}
